[Distribution]
Distribution=debian
Release=bookworm

[Output]
Format=disk
Bootable=yes
ReadOnly=yes

[Content]
Packages=python3,python3-venv,pciutils,dmidecode,fwupd,iproute2,ethtool,smartmontools,tcpdump,ipmitool,efibootmgr,systemd-boot

[Runtime]
Volatile=yes

[Host]
Incremental=yes
